name: 'datawarehouse_dbt'
version: '1.0.0'
config-version: 2

profile: 'datawarehouse'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  datawarehouse_dbt:
    staging:
      materialized: view
      schema: staging
      tags: ['staging']
    intermediate:
      materialized: table
      schema: intermediate
      tags: ['intermediate']
    marts:
      materialized: table
      schema: marts
      tags: ['marts']

vars:
  start_date: '2020-01-01'
  timezone: 'Asia/Shanghai'
