datawarehouse:
  target: dev
  outputs:
    dev:
      type: mysql
      server: localhost
      port: 3306
      schema: sqlExpert
      username: sqluser
      password: ${MYSQL_PASSWORD}
      database: sqlExpert
    
    mysql:
      type: mysql
      server: localhost
      port: 3306
      schema: sqlExpert
      username: sqluser
      password: ${MYSQL_PASSWORD}
      database: sqlExpert
    
    postgres:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: ${POSTGRES_PASSWORD}
      dbname: sqlExpert
      schema: public
    
    greenplum:
      type: postgres
      host: gp-master
      port: 5432
      user: gpadmin
      password: ${GP_PASSWORD}
      dbname: sqlExpert
      schema: public
